const SEED_DATA = Object.freeze({
  users: Object.freeze([
    Object.freeze({
      id: 'u-artem',
      email: 'organizer@travel-assistant.demo',
      name: 'Организатор демо',
      initials: 'ОД',
    }),
    Object.freeze({
      id: 'u-anna',
      email: 'participant@travel-assistant.demo',
      name: 'Участник демо',
      initials: 'УД',
    }),
    Object.freeze({
      id: 'u-no-access',
      email: 'no-access@travel-assistant.demo',
      name: 'Пользователь без доступа',
      initials: 'БД',
    }),
  ]),
  trip: Object.freeze({
    id: 'trip-turkey-2026',
    title: 'Стамбул — лето 2026',
    route: 'Москва → Стамбул → Москва',
    startDate: '2026-08-10T06:00:00.000Z',
    endDate: '2026-08-16T20:00:00.000Z',
    timezone: 'Europe/Istanbul',
    type: 'group',
    status: 'active',
    ownerId: 'u-artem',
  }),
  participants: Object.freeze([
    Object.freeze({ id: 'member-organizer', userId: 'u-artem', role: 'organizer' }),
    Object.freeze({ id: 'member-participant', userId: 'u-anna', role: 'participant' }),
  ]),
  events: Object.freeze([
    Object.freeze({
      id: 'event-outbound-flight',
      type: 'flight',
      title: 'Перелёт в Стамбул',
      startsAt: '2026-08-10T06:00:00.000Z',
      endsAt: '2026-08-10T10:15:00.000Z',
      status: 'changed',
      departure: 'Москва',
      arrival: 'Стамбул',
    }),
    Object.freeze({
      id: 'event-hotel-checkin',
      type: 'hotel',
      title: 'Заселение в демо-отель',
      startsAt: '2026-08-10T12:00:00.000Z',
      endsAt: '2026-08-16T08:00:00.000Z',
      status: 'scheduled',
      arrival: 'Стамбул',
    }),
  ]),
  documents: Object.freeze([
    Object.freeze({
      id: 'doc-shared-itinerary',
      ownerUserId: 'u-artem',
      name: 'Демо-маршрут.txt',
      type: 'itinerary',
      mimeType: 'text/plain',
      visibility: 'shared',
      status: 'confirmed',
      ocrStatus: 'extracted',
      extractedText: 'Безопасный демонстрационный маршрут без персональных данных.',
      safeDemo: true,
    }),
    Object.freeze({
      id: 'doc-participant-voucher',
      ownerUserId: 'u-artem',
      allowedUserId: 'u-anna',
      name: 'Демо-ваучер участника.txt',
      type: 'voucher',
      mimeType: 'text/plain',
      visibility: 'personal',
      status: 'confirmed',
      ocrStatus: 'extracted',
      extractedText: 'Учебный ваучер без реального номера бронирования.',
      safeDemo: true,
    }),
    Object.freeze({
      id: 'doc-organizer-note',
      ownerUserId: 'u-artem',
      name: 'Внутренняя памятка.txt',
      type: 'note',
      mimeType: 'text/plain',
      visibility: 'organizer_only',
      status: 'confirmed',
      ocrStatus: 'extracted',
      extractedText: 'Учебная внутренняя памятка организатора.',
      safeDemo: true,
    }),
  ]),
  incident: Object.freeze({
    id: 'incident-flight-change-1',
    type: 'flight_change',
    label: 'Изменение времени вылета',
    detail: 'Учебный рейс перенесён, требуется выбрать безопасный вариант.',
    severity: 'warning',
    segment: 'Москва → Стамбул',
    source: 'demo_monitoring',
    status: 'confirmed',
    occurredAt: '2026-08-09T12:00:00.000Z',
    confirmedAt: '2026-08-09T12:05:00.000Z',
  }),
  plans: Object.freeze([
    Object.freeze({
      id: 'plan-fast',
      rank: 1,
      strategy: 'fast',
      title: 'Быстро и экономно',
      summary: 'Подтвердить новый вылет и самостоятельно скорректировать трансфер.',
      steps: ['Проверить новое время', 'Перенести трансфер', 'Сообщить участникам'],
      pros: 'Минимальные расходы и быстрое решение.',
      cons: 'Организатор выполняет координацию самостоятельно.',
      whenToUse: 'Если новое время подходит всей группе.',
    }),
    Object.freeze({
      id: 'plan-reliable',
      rank: 2,
      strategy: 'reliable',
      title: 'Надёжно и комфортно',
      summary: 'Выбрать более удобный альтернативный рейс с запасом времени.',
      steps: ['Запросить альтернативу', 'Подтвердить места', 'Обновить маршрут'],
      pros: 'Больше времени на пересадки и ниже операционный риск.',
      cons: 'Возможна доплата и более позднее прибытие.',
      whenToUse: 'Если важнее предсказуемость и комфорт.',
    }),
    Object.freeze({
      id: 'plan-delegate',
      rank: 3,
      strategy: 'delegate',
      title: 'Минимум усилий',
      summary: 'Передать переоформление перевозчику или агенту.',
      steps: ['Открыть обращение', 'Передать данные брони', 'Дождаться подтверждения'],
      pros: 'Минимум ручной координации со стороны группы.',
      cons: 'Срок решения зависит от поддержки провайдера.',
      whenToUse: 'Если нет времени самостоятельно менять сегменты.',
    }),
  ]),
  message: Object.freeze({
    id: 'message-organizer-seed',
    authorUserId: 'u-artem',
    title: 'Изменение рейса подтверждено',
    content: 'Организатор проверяет три варианта. Итоговое решение будет опубликовано отдельно.',
    audience: { type: 'all-participants', participantIds: [] },
    status: 'published',
    publishedAt: '2026-08-09T12:10:00.000Z',
  }),
  preferences: Object.freeze([
    Object.freeze({ siteUserId: 'u-artem', timezone: 'Europe/Moscow' }),
    Object.freeze({ siteUserId: 'u-anna', timezone: 'Europe/Moscow' }),
  ]),
});

module.exports = { SEED_DATA };
